version: '3'
services:
  # zk
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=zookeeper
      
  # kafka
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

  #mariadb   
  mariadb-docker-container:
    container_name: mariadb-docker-container
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=Root@1234
      - MYSQL_DATABASE=demo
      - MYSQL_USER=demo
      - MYSQL_PASSWORD=Demo@1234
    ports:
      - "3316:3306"
    volumes:
      - /data/mysql
      
  # booking-saga    
  booking-saga:
    image: booking-saga-image
    build:
      context: ./booking-saga
      dockerfile: Dockerfile
    depends_on:
      - kafka
    ports:
      - 8090:8080
    volumes:
      - /data/booking-saga
    links:
      - kafka:kafka
      
  # booking-car
  booking-car:
    image: booking-car-image
    build:
      context: ./booking-car
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - mariadb-docker-container
    ports:
      - 8091:8080
    volumes:
      - /data/booking-car
    links:
      - kafka:kafka   
      
  # booking-hotel
  booking-hotel:
    image: booking-hotel-image
    build:
      context: ./booking-hotel
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - mariadb-docker-container
    ports:
      - 8092:8080
    volumes:
      - /data/booking-hotel
    links:
      - kafka:kafka   

 