spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        booked-car-out:
          destination: bookingCar
          contentType: application/json
        booked-hotel-out:
          destination: bookingHotel
          contentType: application/json
          
        compensation-car-out:
          destination: compensatingCar
          contentType: application/json
        compensation-hotel-out:
          destination: compensatingHotel
          contentType: application/json